version: '3.8'
services:
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=taufique
      - RABBITMQ_DEFAULT_PASS=taufique
    ports:
      - '5672:5672'
      - '15672:15672'